### PR TITLE
bug fix for summary

### LINKED ISSUE #72: Fix album search
When user searches for an album with no summary an error is returned and no results are displayed.

See example response and error below:

image

### PR DESCRIPTION
**Pull request by abc-1211**

### CODE REVIEW

File: assets/script.js [hunk 1]
```diff
@@ -65,12 +65,17 @@ function getAlbumInfo() {
     console.log(response);
     //album search result shown
     var icon = response.album.image[2]["#text"];
-    var summary = response.album.wiki.summary;
     var albumName = response.album.name;
     $("#album-pic").attr("src", icon);
     $("#summaryHeading").text(albumName);
-    $("#summary").html(summary);
     $(".search-tracks>ol").html("");
+    if (response && response.album['wiki']){
```
Comment (Goldenaries658) [inline assets/script.js]: Here you are evaluating if the response and the summary are === to true which they never will be as they are an object/string. You need to evaluate for false which will include null/undefined

Comment (Goldenaries658) [reply assets/script.js]: `response.album['wiki']` inconsistent notation, why not just use .

File: assets/script.js [hunk 2]
```diff
@@ -65,12 +65,17 @@ function getAlbumInfo() {
...
+      var summary = response.album.wiki.summary;
+      $("#summary").html(summary);
+      $("#summary").show();
+    } else {
+      $("#summary").hide();
+    }
```
Comment (Goldenaries658) [inline assets/script.js]:
```suggestion
    if (!response.album.wiki.summary){
      $("#summary").hide();
    } else {
      $("#summary").html(response.album.wiki.summary);
      $("#summary").show();    
    }
```

**Review by Goldenaries658 — CHANGES_REQUESTED** [review]

**Review by Goldenaries658 — APPROVED** [review]
